// <auto-generated> welder C#/.NET bindings. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
#nullable enable
using System;
using System.Runtime.InteropServices;

namespace csharp_cases
{
    /// <summary>The native error slot every welder thunk fills (code 0 = success).</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderError
    {
        public int Code;
        public IntPtr Message;
    }

    /// <summary>A C++ exception that crossed the native boundary.</summary>
    public class WelderNativeException : Exception
    {
        public int NativeCode { get; }
        public WelderNativeException(int code, string message) : base(message)
        {
            NativeCode = code;
        }
    }

    internal static class WelderInterop
    {
        internal static void ThrowIfError(in WelderError err)
        {
            if (err.Code == 0) return;
            string msg = "";
            if (err.Message != IntPtr.Zero)
            {
                msg = Marshal.PtrToStringUTF8(err.Message) ?? "";
                NativeMethods.welder_free(err.Message);
            }
            throw err.Code switch
            {
                2 => new OutOfMemoryException(msg),
                3 => new ArgumentException(msg),
                4 => new ArgumentOutOfRangeException(null, msg),
                5 => new ArithmeticException(msg),
                _ => (Exception)new WelderNativeException(err.Code, msg),
            };
        }
    }

    internal static partial class NativeMethods
    {
        internal const string Lib = "welder_test_csharp_native";

        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_1(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_clone(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_x(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_x(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_y(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_y(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_stamp(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_m_sum_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_1(PointHandle self, int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_label_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial Color welder_csharp_cases_Point_m_hue_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_translated_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_s_origin_0(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_explode_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_pget_Depth(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_pset_Depth(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_op_plus_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Point_op_equals_equals_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_agg(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_clone(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_width(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_width(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_height(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_height(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Holder_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_clone(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_copy_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_peek_0(HolderHandle self, [MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Holder_m_item_x_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_make_point_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_f_reject_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_1(PointHandle a0, PointHandle a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_clone(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_start(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_start(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_end(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_end(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Segment_m_span_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Segment_m_degenerate_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_add_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_csharp_cases_f_greet_0(string a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_v_answer_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_v_answer_set(int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial double welder_csharp_cases_v_golden_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_inner_f_twice_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_free(IntPtr p);
    }

    /// <summary>Primary display colors.</summary>
    public enum Color : int
    {
        Red = 0,
        Green = 1,
        Blue = 2,
    }

    public enum Level : byte
    {
        Low = 1,
        High = 200,
    }

    internal sealed class PointHandle : SafeHandle
    {
        internal PointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A 2-D integer point.</summary>
    public sealed class Point : IDisposable
    {
        internal PointHandle _handle;
        internal object? __owner;
        internal Point(IntPtr handle, bool owns) { _handle = new PointHandle(handle, owns); }

        public Point()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new PointHandle(__r, true);
        }

        public Point(int x_, int y_)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_new_1(x_, y_, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new PointHandle(__r, true);
        }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Point Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_clone(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public int X
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_x(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_x(_handle, value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Y
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_y(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_y(_handle, value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Stamp
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_stamp(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
        }

        public int Sum()
        {
            var __r = NativeMethods.welder_csharp_cases_Point_m_sum_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public void Offset(int dx, int dy)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_0(_handle, dx, dy, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public void Offset(int d)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_1(_handle, d, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public string Label()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_m_label_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public Color Hue()
        {
            var __r = NativeMethods.welder_csharp_cases_Point_m_hue_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public Point Translated(int dx, int dy)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_m_translated_0(_handle, dx, dy, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public static Point Origin()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_s_origin_0(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public void Explode()
        {
            NativeMethods.welder_csharp_cases_Point_m_explode_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public int Depth
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_pget_Depth(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_pset_Depth(_handle, value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public static Point operator +(Point l, Point r)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_op_plus_b_0(l._handle, r._handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public static bool operator ==(Point? l, Point? r)
        {
            if (ReferenceEquals(l, r)) return true;
            if (l is null || r is null) return false;
            var __r = NativeMethods.welder_csharp_cases_Point_op_equals_equals_b_0(l._handle, r._handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public static bool operator !=(Point? l, Point? r) => !(l == r);

        public override bool Equals(object? obj) => obj is Point __o && this == __o;
        /// <summary>Reference-identity hash (the C++ type has no hash to mirror).</summary>
        public override int GetHashCode() => base.GetHashCode();

        public void Dispose() => _handle.Dispose();
    }

    internal sealed class SizeHandle : SafeHandle
    {
        internal SizeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Size_destroy(handle);
            return true;
        }
    }

    public sealed class Size : IDisposable
    {
        internal SizeHandle _handle;
        internal object? __owner;
        internal Size(IntPtr handle, bool owns) { _handle = new SizeHandle(handle, owns); }

        public Size()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new SizeHandle(__r, true);
        }

        public Size(int width, int height)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_new_agg(width, height, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new SizeHandle(__r, true);
        }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Size Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_clone(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Size(__r, true);
        }

        public int Width
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Size_get_width(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_width(_handle, value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Height
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Size_get_height(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_height(_handle, value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public void Dispose() => _handle.Dispose();
    }

    internal sealed class HolderHandle : SafeHandle
    {
        internal HolderHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Holder_destroy(handle);
            return true;
        }
    }

    public sealed class Holder : IDisposable
    {
        internal HolderHandle _handle;
        internal object? __owner;
        internal Holder(IntPtr handle, bool owns) { _handle = new HolderHandle(handle, owns); }

        public Holder()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new HolderHandle(__r, true);
        }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Holder Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_clone(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Holder(__r, true);
        }

        public Point Item()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_item_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            var __v = new Point(__r, false);
            __v.__owner = this;
            return __v;
        }

        public Point ItemCopy()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_item_copy_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public Point? Peek(bool give)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_peek_0(_handle, give, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            if (__r == IntPtr.Zero) return null;
            var __v = new Point(__r, false);
            return __v;
        }

        public int ItemX()
        {
            var __r = NativeMethods.welder_csharp_cases_Holder_m_item_x_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public void Dispose() => _handle.Dispose();
    }

    internal sealed class SegmentHandle : SafeHandle
    {
        internal SegmentHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Segment_destroy(handle);
            return true;
        }
    }

    public sealed class Segment : IDisposable
    {
        internal SegmentHandle _handle;
        internal object? __owner;
        internal Segment(IntPtr handle, bool owns) { _handle = new SegmentHandle(handle, owns); }

        public Segment()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new SegmentHandle(__r, true);
        }

        public Segment(Point a, Point b)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_new_1(a._handle, b._handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            _handle = new SegmentHandle(__r, true);
        }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Segment Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_clone(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Segment(__r, true);
        }

        public Point Start
        {
            get
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Segment_get_start(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new Point(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_start(_handle, value._handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public Point End
        {
            get
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Segment_get_end(_handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new Point(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_end(_handle, value._handle, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Span()
        {
            var __r = NativeMethods.welder_csharp_cases_Segment_m_span_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public bool Degenerate()
        {
            var __r = NativeMethods.welder_csharp_cases_Segment_m_degenerate_0(_handle, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public void Dispose() => _handle.Dispose();
    }

    public static class Global
    {
        public static Point? MakePoint(int x, int y)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_f_make_point_0(x, y, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            if (__r == IntPtr.Zero) return null;
            return new Point(__r, true);
        }

        public static void Reject(int v)
        {
            NativeMethods.welder_csharp_cases_f_reject_0(v, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        /// <summary>Add two numbers.</summary>
        public static int Add(int a, int b)
        {
            var __r = NativeMethods.welder_csharp_cases_f_add_0(a, b, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public static string Greet(string name)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_f_greet_0(name, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public static int Answer
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_v_answer_get(out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_v_answer_set(value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public static double Golden
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_v_golden_get(out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
        }

    }

    public static class Inner
    {
        public static int Twice(int v)
        {
            var __r = NativeMethods.welder_csharp_cases_inner_f_twice_0(v, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

    }

}
