// <auto-generated> welder C#/.NET bindings. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace csharp_cases
{
    /// <summary>The native error slot every welder thunk fills (code 0 = success).</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderError
    {
        public int Code;
        public IntPtr Message;
    }

    /// <summary>A C++ exception that crossed the native boundary.</summary>
    public class WelderNativeException : Exception
    {
        public int NativeCode { get; }
        public WelderNativeException(int code, string message) : base(message)
        {
            NativeCode = code;
        }
    }

    /// <summary>The by-value wire of an optional with a leaf payload.</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderOptWire
    {
        public byte Has;
        public long I;
        public double F;
        public IntPtr S;
        public IntPtr P;
    }

    /// <summary>The by-value wire of a scalar/enum sequence (buffer + length).</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderSeqWire
    {
        public IntPtr Data;
        public long Len;
    }

    /// <summary>The by-value wire of a shared_ptr return: the object plus the boxed
    /// shared_ptr copy pinning it.</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderSpWire
    {
        public IntPtr Obj;
        public IntPtr Box;
    }

    internal static class WelderInterop
    {
        internal static void ThrowIfError(in WelderError err)
        {
            if (err.Code == 0) return;
            string msg = "";
            if (err.Message != IntPtr.Zero)
            {
                msg = Marshal.PtrToStringUTF8(err.Message) ?? "";
                NativeMethods.welder_free(err.Message);
            }
            throw err.Code switch
            {
                2 => new OutOfMemoryException(msg),
                3 => new ArgumentException(msg),
                4 => new ArgumentOutOfRangeException(null, msg),
                5 => new ArithmeticException(msg),
                _ => (Exception)new WelderNativeException(err.Code, msg),
            };
        }
    }

    internal static partial class NativeMethods
    {
        internal const string Lib = "welder_test_csharp_native";

        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_1(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_clone(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_x(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_x(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_y(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_y(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_stamp(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_m_sum_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_1(PointHandle self, int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_label_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial Color welder_csharp_cases_Point_m_hue_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_translated_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_s_origin_0(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_explode_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_pget_Depth(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_pset_Depth(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_op_plus_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Point_op_equals_equals_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_agg(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_clone(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_width(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_width(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_height(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_height(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Holder_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_clone(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_copy_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_peek_0(HolderHandle self, [MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Holder_m_item_x_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_make_point_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_f_tagged_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial long welder_csharp_cases_f_pair_sum_0(IntPtr a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_f_bundle_0(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_f_reject_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_1(PointHandle a0, PointHandle a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_clone(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_start(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_start(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_end(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_end(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Segment_m_span_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Segment_m_degenerate_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_add_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_csharp_cases_f_greet_0(string a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_v_answer_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_v_answer_set(int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial double welder_csharp_cases_v_golden_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Animal_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_clone(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Animal_get_age(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Animal_set_age(AnimalHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_m_kind_0(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Legged_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Legged_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Legged_clone(LeggedHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Legged_get_legs(LeggedHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Legged_set_legs(LeggedHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_as_csharp_cases_Animal(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_as_csharp_cases_Legged(IntPtr self);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Dog_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_clone(DogHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_m_bark_0(DogHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_age_of_0(AnimalHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Basket_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Basket_clone(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_Basket_get_nums(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_set_nums(BasketHandle self, WelderSeqWire v, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_Basket_get_label(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_set_label(BasketHandle self, WelderOptWire v, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_Basket_m_find_0(BasketHandle self, int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial long welder_csharp_cases_Basket_m_total_0(BasketHandle self, WelderSeqWire a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_Basket_m_triple_0(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_m_set_triple_0(BasketHandle self, WelderSeqWire a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial double welder_csharp_cases_Basket_m_trip_sum_0(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_f_maybe_point_0([MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_f_maybe_level_0([MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Route_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_clone(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_vec_csharp_cases_Point_new(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial long welder_vec_csharp_cases_Point_size(VectorPointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_vec_csharp_cases_Point_get(VectorPointHandle self, long i, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_set(VectorPointHandle self, long i, PointHandle elem, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_add(VectorPointHandle self, PointHandle elem, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_clear(VectorPointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_get_stops(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Route_set_stops(RouteHandle self, VectorPointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Route_m_stop_count_0(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_m_reversed_0(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Route_m_total_x_0(RouteHandle self, VectorPointHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Depot_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Depot_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Depot_clone(DepotHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_map_str_csharp_cases_Point_new(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_map_str_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial long welder_map_str_csharp_cases_Point_size(MapStrPointHandle self, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_map_str_csharp_cases_Point_contains(MapStrPointHandle self, string k, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_map_str_csharp_cases_Point_get(MapStrPointHandle self, string k, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial void welder_map_str_csharp_cases_Point_set(MapStrPointHandle self, string k, PointHandle v, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_map_str_csharp_cases_Point_remove(MapStrPointHandle self, string k, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_map_str_csharp_cases_Point_clear(MapStrPointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Depot_get_sites(DepotHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Depot_set_sites(DepotHandle self, MapStrPointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_umap_int_str_new(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_umap_int_str_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial long welder_umap_int_str_size(UMapIntStrHandle self, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_umap_int_str_contains(UMapIntStrHandle self, int k, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_umap_int_str_get(UMapIntStrHandle self, int k, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial void welder_umap_int_str_set(UMapIntStrHandle self, int k, string v, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_umap_int_str_remove(UMapIntStrHandle self, int k, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_umap_int_str_clear(UMapIntStrHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Depot_get_labels(DepotHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Depot_set_labels(DepotHandle self, UMapIntStrHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Depot_m_site_count_0(DepotHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial long welder_csharp_cases_Depot_m_label_keys_0(DepotHandle self, UMapIntStrHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Cable_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Cable_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Cable_clone(CableHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_arr2_csharp_cases_Point_new(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_arr2_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_arr2_csharp_cases_Point_get(ArrayPointx2Handle self, long i, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_arr2_csharp_cases_Point_set(ArrayPointx2Handle self, long i, PointHandle elem, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Cable_get_ends(CableHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Cable_set_ends(CableHandle self, ArrayPointx2Handle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Cable_m_span_x_0(CableHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_sp_csharp_cases_Point_free(IntPtr box);
        [LibraryImport(Lib)] internal static partial WelderSpWire welder_csharp_cases_f_shared_point_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSpWire welder_csharp_cases_f_no_point_0(out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_shared_x_0(IntPtr a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_unique_point_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_dir_init(IntPtr release, IntPtr s0, IntPtr s1);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_dir_bind(IntPtr self, IntPtr ctx, ulong mask);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_clone(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_name_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_name_0_base(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Shape_m_sides_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Shape_m_sides_0_base(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_describe_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_describe_shape_0(ShapeHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_Gauge_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_Gauge_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_Gauge_new_1(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_Gauge_clone(Machine.GaugeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Machine_Gauge_get_value(Machine.GaugeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_Gauge_set_value(Machine.GaugeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_clone(MachineHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial Machine.State welder_csharp_cases_Machine_get_power(MachineHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_set_power(MachineHandle self, Machine.State v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_get_dial(MachineHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_set_dial(MachineHandle self, Machine.GaugeHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Machine_m_turn_on_0(MachineHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Machine_m_peak_0(MachineHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_inner_f_twice_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_free(IntPtr p);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_dup_utf8(string s);
    }

    /// <summary>Primary display colors.</summary>
    public enum Color : int
    {
        Red = 0,
        Green = 1,
        Blue = 2,
    }

    public enum Level : byte
    {
        Low = 1,
        High = 200,
    }

    internal sealed class PointHandle : SafeHandle
    {
        internal PointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A 2-D integer point.</summary>
    public class Point : IDisposable
    {
        internal PointHandle _h_Point;
        internal object? _owner;
        internal bool _isDirector;
        internal Point(IntPtr handle, bool owns) { _h_Point = new PointHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Point() : this(_New_default(), true) {}

        private static IntPtr _New_1(int x_, int y_)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_new_1(x_, y_, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Point(int x_, int y_) : this(_New_1(x_, y_), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Point Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_clone(_h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Point(_r, true);
        }

        public int X
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Point_get_x(_h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_x(_h_Point, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int Y
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Point_get_y(_h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_y(_h_Point, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int Stamp
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Point_get_stamp(_h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
        }

        public int Sum()
        {
            var _r = NativeMethods.welder_csharp_cases_Point_m_sum_0(_h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public void Offset(int dx, int dy)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_0(_h_Point, dx, dy, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }

        public void Offset(int d)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_1(_h_Point, d, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }

        public string Label()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_m_label_0(_h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

        public Color Hue()
        {
            var _r = NativeMethods.welder_csharp_cases_Point_m_hue_0(_h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public Point Translated(int dx, int dy)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_m_translated_0(_h_Point, dx, dy, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Point(_r, true);
        }

        public static Point Origin()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_s_origin_0(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Point(_r, true);
        }

        public void Explode()
        {
            NativeMethods.welder_csharp_cases_Point_m_explode_0(_h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }

        public int Depth
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Point_pget_Depth(_h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_pset_Depth(_h_Point, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public static Point operator +(Point l, Point r)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Point_op_plus_b_0(l._h_Point, r._h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Point(_r, true);
        }

        public static bool operator ==(Point? l, Point? r)
        {
            if (ReferenceEquals(l, r)) return true;
            if (l is null || r is null) return false;
            var _r = NativeMethods.welder_csharp_cases_Point_op_equals_equals_b_0(l._h_Point, r._h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public static bool operator !=(Point? l, Point? r) => !(l == r);

        public override bool Equals(object? obj) => obj is Point _o && this == _o;
        /// <summary>Reference-identity hash (the C++ type has no hash to mirror).</summary>
        public override int GetHashCode() => base.GetHashCode();

        public virtual void Dispose() => _h_Point.Dispose();
    }

    internal sealed class SizeHandle : SafeHandle
    {
        internal SizeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Size_destroy(handle);
            return true;
        }
    }

    public class Size : IDisposable
    {
        internal SizeHandle _h_Size;
        internal object? _owner;
        internal bool _isDirector;
        internal Size(IntPtr handle, bool owns) { _h_Size = new SizeHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Size_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Size() : this(_New_default(), true) {}

        private static IntPtr _New_agg(int width, int height)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Size_new_agg(width, height, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Size(int width, int height) : this(_New_agg(width, height), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Size Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Size_clone(_h_Size, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Size(_r, true);
        }

        public int Width
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Size_get_width(_h_Size, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_width(_h_Size, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int Height
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Size_get_height(_h_Size, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_height(_h_Size, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public virtual void Dispose() => _h_Size.Dispose();
    }

    internal sealed class HolderHandle : SafeHandle
    {
        internal HolderHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Holder_destroy(handle);
            return true;
        }
    }

    public class Holder : IDisposable
    {
        internal HolderHandle _h_Holder;
        internal object? _owner;
        internal bool _isDirector;
        internal Holder(IntPtr handle, bool owns) { _h_Holder = new HolderHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Holder_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Holder() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Holder Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Holder_clone(_h_Holder, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Holder(_r, true);
        }

        public Point Item()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Holder_m_item_0(_h_Holder, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            var _v = new Point(_r, false);
            _v._owner = this;
            return _v;
        }

        public Point ItemCopy()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Holder_m_item_copy_0(_h_Holder, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Point(_r, true);
        }

        public Point? Peek(bool give)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Holder_m_peek_0(_h_Holder, give, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            if (_r == IntPtr.Zero) return null;
            var _v = new Point(_r, false);
            return _v;
        }

        public int ItemX()
        {
            var _r = NativeMethods.welder_csharp_cases_Holder_m_item_x_0(_h_Holder, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Holder.Dispose();
    }

    internal sealed class SegmentHandle : SafeHandle
    {
        internal SegmentHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Segment_destroy(handle);
            return true;
        }
    }

    public class Segment : IDisposable
    {
        internal SegmentHandle _h_Segment;
        internal object? _owner;
        internal bool _isDirector;
        internal Segment(IntPtr handle, bool owns) { _h_Segment = new SegmentHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Segment_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Segment() : this(_New_default(), true) {}

        private static IntPtr _New_1(Point a, Point b)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Segment_new_1(a._h_Point, b._h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Segment(Point a, Point b) : this(_New_1(a, b), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Segment Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Segment_clone(_h_Segment, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Segment(_r, true);
        }

        public Point Start
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Segment_get_start(_h_Segment, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Point(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_start(_h_Segment, @value._h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public Point End
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Segment_get_end(_h_Segment, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Point(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_end(_h_Segment, @value._h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int Span()
        {
            var _r = NativeMethods.welder_csharp_cases_Segment_m_span_0(_h_Segment, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public bool Degenerate()
        {
            var _r = NativeMethods.welder_csharp_cases_Segment_m_degenerate_0(_h_Segment, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Segment.Dispose();
    }

    internal sealed class AnimalHandle : SafeHandle
    {
        internal AnimalHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Animal_destroy(handle);
            return true;
        }
    }

    public class Animal : IDisposable
    {
        internal AnimalHandle _h_Animal;
        internal object? _owner;
        internal bool _isDirector;
        internal Animal(IntPtr handle, bool owns) { _h_Animal = new AnimalHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Animal_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Animal() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Animal Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Animal_clone(_h_Animal, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Animal(_r, true);
        }

        public int Age
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Animal_get_age(_h_Animal, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Animal_set_age(_h_Animal, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public string Kind()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Animal_m_kind_0(_h_Animal, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

        public virtual void Dispose() => _h_Animal.Dispose();
    }

    internal sealed class LeggedHandle : SafeHandle
    {
        internal LeggedHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Legged_destroy(handle);
            return true;
        }
    }

    public class Legged : IDisposable
    {
        internal LeggedHandle _h_Legged;
        internal object? _owner;
        internal bool _isDirector;
        internal Legged(IntPtr handle, bool owns) { _h_Legged = new LeggedHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Legged_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Legged() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Legged Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Legged_clone(_h_Legged, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Legged(_r, true);
        }

        public int Legs
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Legged_get_legs(_h_Legged, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Legged_set_legs(_h_Legged, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public virtual void Dispose() => _h_Legged.Dispose();
    }

    internal sealed class DogHandle : SafeHandle
    {
        internal DogHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Dog_destroy(handle);
            return true;
        }
    }

    public class Dog : Animal
    {
        internal DogHandle _h_Dog;
        internal Dog(IntPtr handle, bool owns) : base(NativeMethods.welder_csharp_cases_Dog_as_csharp_cases_Animal(handle), false) { _h_Dog = new DogHandle(handle, owns); }

        /// <summary>This object's Legged base surface (a non-owning view).</summary>
        public Legged AsLegged()
        {
            IntPtr _p = NativeMethods.welder_csharp_cases_Dog_as_csharp_cases_Legged(_h_Dog.DangerousGetHandle());
            GC.KeepAlive(this);
            var _v = new Legged(_p, false);
            _v._owner = this;
            return _v;
        }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Dog_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Dog() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Dog Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Dog_clone(_h_Dog, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Dog(_r, true);
        }

        public string Bark()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Dog_m_bark_0(_h_Dog, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

        public override void Dispose() { _h_Dog.Dispose(); base.Dispose(); }
    }

    internal sealed class BasketHandle : SafeHandle
    {
        internal BasketHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Basket_destroy(handle);
            return true;
        }
    }

    public class Basket : IDisposable
    {
        internal BasketHandle _h_Basket;
        internal object? _owner;
        internal bool _isDirector;
        internal Basket(IntPtr handle, bool owns) { _h_Basket = new BasketHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Basket_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Basket() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Basket Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Basket_clone(_h_Basket, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Basket(_r, true);
        }

        public unsafe int[] Nums
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Basket_get_nums(_h_Basket, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _out = new int[_r.Len];
                if (_r.Len != 0)
                {
                    fixed (int* _d = _out)
                        Buffer.MemoryCopy((void*)_r.Data, _d, _r.Len * sizeof(int), _r.Len * sizeof(int));
                }
                if (_r.Data != IntPtr.Zero) NativeMethods.welder_free(_r.Data);
                return _out;
            }
            set
            {
                fixed (int* _pin0 = @value) {
                NativeMethods.welder_csharp_cases_Basket_set_nums(_h_Basket, new WelderSeqWire { Data = (IntPtr)_pin0, Len = @value.Length }, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                }
            }
        }

        public string? Label
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Basket_get_label(_h_Basket, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                if (_r.Has == 0) return null;
                IntPtr _s = _r.S;
                try { return Marshal.PtrToStringUTF8(_s) ?? ""; }
                finally { NativeMethods.welder_free(_s); }
            }
            set
            {
                NativeMethods.welder_csharp_cases_Basket_set_label(_h_Basket, @value is null ? default : new WelderOptWire { Has = 1, S = NativeMethods.welder_dup_utf8(@value) }, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int? Find(int v)
        {
            var _r = NativeMethods.welder_csharp_cases_Basket_m_find_0(_h_Basket, v, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r.Has != 0 ? (int?)unchecked((int)_r.I) : null;
        }

        public unsafe long Total(int[] extra)
        {
            fixed (int* _pin0 = extra) {
            var _r = NativeMethods.welder_csharp_cases_Basket_m_total_0(_h_Basket, new WelderSeqWire { Data = (IntPtr)_pin0, Len = extra.Length }, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
            }
        }

        public unsafe double[] Triple()
        {
            var _r = NativeMethods.welder_csharp_cases_Basket_m_triple_0(_h_Basket, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            var _out = new double[_r.Len];
            if (_r.Len != 0)
            {
                fixed (double* _d = _out)
                    Buffer.MemoryCopy((void*)_r.Data, _d, _r.Len * sizeof(double), _r.Len * sizeof(double));
            }
            if (_r.Data != IntPtr.Zero) NativeMethods.welder_free(_r.Data);
            return _out;
        }

        public unsafe void SetTriple(double[] a)
        {
            fixed (double* _pin0 = a) {
            NativeMethods.welder_csharp_cases_Basket_m_set_triple_0(_h_Basket, new WelderSeqWire { Data = (IntPtr)_pin0, Len = a.Length }, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            }
        }

        public double TripSum()
        {
            var _r = NativeMethods.welder_csharp_cases_Basket_m_trip_sum_0(_h_Basket, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Basket.Dispose();
    }

    internal sealed class RouteHandle : SafeHandle
    {
        internal RouteHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Route_destroy(handle);
            return true;
        }
    }

    public class Route : IDisposable
    {
        internal RouteHandle _h_Route;
        internal object? _owner;
        internal bool _isDirector;
        internal Route(IntPtr handle, bool owns) { _h_Route = new RouteHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Route_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Route() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Route Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Route_clone(_h_Route, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Route(_r, true);
        }

        public VectorPoint Stops
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Route_get_stops(_h_Route, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new VectorPoint(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Route_set_stops(_h_Route, @value._h_VectorPoint, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int StopCount()
        {
            var _r = NativeMethods.welder_csharp_cases_Route_m_stop_count_0(_h_Route, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public VectorPoint Reversed()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Route_m_reversed_0(_h_Route, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new VectorPoint(_r, true);
        }

        public int TotalX(VectorPoint pts)
        {
            var _r = NativeMethods.welder_csharp_cases_Route_m_total_x_0(_h_Route, pts._h_VectorPoint, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Route.Dispose();
    }

    internal sealed class DepotHandle : SafeHandle
    {
        internal DepotHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Depot_destroy(handle);
            return true;
        }
    }

    public class Depot : IDisposable
    {
        internal DepotHandle _h_Depot;
        internal object? _owner;
        internal bool _isDirector;
        internal Depot(IntPtr handle, bool owns) { _h_Depot = new DepotHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Depot_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Depot() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Depot Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Depot_clone(_h_Depot, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Depot(_r, true);
        }

        public MapStrPoint Sites
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Depot_get_sites(_h_Depot, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new MapStrPoint(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Depot_set_sites(_h_Depot, @value._h_MapStrPoint, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public UMapIntStr Labels
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Depot_get_labels(_h_Depot, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new UMapIntStr(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Depot_set_labels(_h_Depot, @value._h_UMapIntStr, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int SiteCount()
        {
            var _r = NativeMethods.welder_csharp_cases_Depot_m_site_count_0(_h_Depot, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public long LabelKeys(UMapIntStr m)
        {
            var _r = NativeMethods.welder_csharp_cases_Depot_m_label_keys_0(_h_Depot, m._h_UMapIntStr, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Depot.Dispose();
    }

    internal sealed class CableHandle : SafeHandle
    {
        internal CableHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Cable_destroy(handle);
            return true;
        }
    }

    public class Cable : IDisposable
    {
        internal CableHandle _h_Cable;
        internal object? _owner;
        internal bool _isDirector;
        internal Cable(IntPtr handle, bool owns) { _h_Cable = new CableHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Cable_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Cable() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Cable Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Cable_clone(_h_Cable, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Cable(_r, true);
        }

        public ArrayPointx2 Ends
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Cable_get_ends(_h_Cable, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new ArrayPointx2(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Cable_set_ends(_h_Cable, @value._h_ArrayPointx2, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public int SpanX()
        {
            var _r = NativeMethods.welder_csharp_cases_Cable_m_span_x_0(_h_Cable, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public virtual void Dispose() => _h_Cable.Dispose();
    }

    internal sealed class ShapeHandle : SafeHandle
    {
        internal ShapeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Shape_destroy(handle);
            return true;
        }
    }

    public class Shape : IDisposable
    {
        internal ShapeHandle _h_Shape;
        internal object? _owner;
        internal bool _isDirector;
        internal Shape(IntPtr handle, bool owns) { _h_Shape = new ShapeHandle(handle, owns); }

        private static bool _cbInit;
        private static unsafe void _EnsureCallbacks()
        {
            if (_cbInit) return;
            _cbInit = true;
            NativeMethods.welder_csharp_cases_Shape_dir_init(
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&_Release,
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, WelderError*, IntPtr>)&_Slot0,
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, WelderError*, int>)&_Slot1);
        }
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static void _Release(IntPtr ctx) => GCHandle.FromIntPtr(ctx).Free();
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static unsafe IntPtr _Slot0(IntPtr _ctx, WelderError* _err)
        {
            try
            {
                var _self = (Shape?)GCHandle.FromIntPtr(_ctx).Target;
                if (_self is null) throw new InvalidOperationException("welder: director target collected");
                return NativeMethods.welder_dup_utf8(_self.Name());
            }
            catch (Exception _ex)
            {
                _err->Code = 7;
                _err->Message = NativeMethods.welder_dup_utf8(_ex.Message);
                return default;
            }
        }
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static unsafe int _Slot1(IntPtr _ctx, WelderError* _err)
        {
            try
            {
                var _self = (Shape?)GCHandle.FromIntPtr(_ctx).Target;
                if (_self is null) throw new InvalidOperationException("welder: director target collected");
                return _self.Sides();
            }
            catch (Exception _ex)
            {
                _err->Code = 7;
                _err->Message = NativeMethods.welder_dup_utf8(_ex.Message);
                return default;
            }
        }
        private static ulong _OverrideMask(Type _t)
        {
            ulong _m = 0;
            if (_t == typeof(Shape)) return _m;
            if (_NotWrapper(_t.GetMethod("Name", new Type[] {  })?.DeclaringType)) _m |= 1UL << 0;
            if (_NotWrapper(_t.GetMethod("Sides", new Type[] {  })?.DeclaringType)) _m |= 1UL << 1;
            return _m;
        }
        private static bool _NotWrapper(Type? _d) =>
            _d is not null && _d != typeof(Shape);
        private void _DirBind()
        {
            _isDirector = true;
            _EnsureCallbacks();
            NativeMethods.welder_csharp_cases_Shape_dir_bind(
                _h_Shape.DangerousGetHandle(),
                GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)),
                _OverrideMask(GetType()));
            GC.KeepAlive(this);
        }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Shape_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Shape() : this(_New_default(), true) { _DirBind(); }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Shape Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Shape_clone(_h_Shape, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Shape(_r, true);
        }

        public virtual string Name()
        {
            if (_isDirector)
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Shape_m_name_0_base(_h_Shape, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
                finally { NativeMethods.welder_free(_r); }
            }
            else
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Shape_m_name_0(_h_Shape, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
                finally { NativeMethods.welder_free(_r); }
            }
        }

        public virtual int Sides()
        {
            if (_isDirector)
            {
                var _r = NativeMethods.welder_csharp_cases_Shape_m_sides_0_base(_h_Shape, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            else
            {
                var _r = NativeMethods.welder_csharp_cases_Shape_m_sides_0(_h_Shape, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
        }

        public string Describe()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Shape_m_describe_0(_h_Shape, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

        public virtual void Dispose() => _h_Shape.Dispose();
    }

    internal sealed class MachineHandle : SafeHandle
    {
        internal MachineHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Machine_destroy(handle);
            return true;
        }
    }

    public class Machine : IDisposable
    {
        internal MachineHandle _h_Machine;
        internal object? _owner;
        internal bool _isDirector;
        internal Machine(IntPtr handle, bool owns) { _h_Machine = new MachineHandle(handle, owns); }

    public enum State : byte
    {
        Off = 0,
        On = 1,
    }

    internal sealed class GaugeHandle : SafeHandle
    {
        internal GaugeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Machine_Gauge_destroy(handle);
            return true;
        }
    }

    public class Gauge : IDisposable
    {
        internal GaugeHandle _h_Machine_Gauge;
        internal object? _owner;
        internal bool _isDirector;
        internal Gauge(IntPtr handle, bool owns) { _h_Machine_Gauge = new GaugeHandle(handle, owns); }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_Gauge_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Gauge() : this(_New_default(), true) {}

        private static IntPtr _New_1(int v)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_Gauge_new_1(v, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Gauge(int v) : this(_New_1(v), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Gauge Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_Gauge_clone(_h_Machine_Gauge, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Gauge(_r, true);
        }

        public int Value
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Machine_Gauge_get_value(_h_Machine_Gauge, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Machine_Gauge_set_value(_h_Machine_Gauge, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public virtual void Dispose() => _h_Machine_Gauge.Dispose();
    }

        private static IntPtr _New_default()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_new_default(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Machine() : this(_New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Machine Clone()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_clone(_h_Machine, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Machine(_r, true);
        }

        public Machine.State Power
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_Machine_get_power(_h_Machine, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Machine_set_power(_h_Machine, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public Machine.Gauge Dial
        {
            get
            {
                IntPtr _r = NativeMethods.welder_csharp_cases_Machine_get_dial(_h_Machine, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Machine.Gauge(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Machine_set_dial(_h_Machine, @value._h_Machine_Gauge, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public void TurnOn()
        {
            NativeMethods.welder_csharp_cases_Machine_m_turn_on_0(_h_Machine, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }

        public Machine.Gauge Peak()
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_Machine_m_peak_0(_h_Machine, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return new Machine.Gauge(_r, true);
        }

        public virtual void Dispose() => _h_Machine.Dispose();
    }

    internal sealed class VectorPointHandle : SafeHandle
    {
        internal VectorPointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_vec_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A reference-semantic C++ vector of Point (live element views).</summary>
    public sealed class VectorPoint : IDisposable
    {
        internal VectorPointHandle _h_VectorPoint;
        internal object? _owner;
        internal VectorPoint(IntPtr handle, bool owns) { _h_VectorPoint = new VectorPointHandle(handle, owns); }
        public VectorPoint() : this(_New(), true) {}
        private static IntPtr _New()
        {
            IntPtr _r = NativeMethods.welder_vec_csharp_cases_Point_new(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public int Count
        {
            get
            {
                var _r = NativeMethods.welder_vec_csharp_cases_Point_size(_h_VectorPoint, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return (int)_r;
            }
        }
        public Point this[int i]
        {
            get
            {
                IntPtr _r = NativeMethods.welder_vec_csharp_cases_Point_get(_h_VectorPoint, i, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Point(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_vec_csharp_cases_Point_set(_h_VectorPoint, i, value._h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }
        public void Add(Point item)
        {
            NativeMethods.welder_vec_csharp_cases_Point_add(_h_VectorPoint, item._h_Point, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }
        public void Clear()
        {
            NativeMethods.welder_vec_csharp_cases_Point_clear(_h_VectorPoint, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }
        public void Dispose() => _h_VectorPoint.Dispose();
    }

    internal sealed class MapStrPointHandle : SafeHandle
    {
        internal MapStrPointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_map_str_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A reference-semantic C++ std::map of string to Point.</summary>
    public sealed class MapStrPoint : IDisposable
    {
        internal MapStrPointHandle _h_MapStrPoint;
        internal object? _owner;
        internal MapStrPoint(IntPtr handle, bool owns) { _h_MapStrPoint = new MapStrPointHandle(handle, owns); }
        public MapStrPoint() : this(_New(), true) {}
        private static IntPtr _New()
        {
            IntPtr _r = NativeMethods.welder_map_str_csharp_cases_Point_new(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public int Count
        {
            get
            {
                var _r = NativeMethods.welder_map_str_csharp_cases_Point_size(_h_MapStrPoint, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return (int)_r;
            }
        }
        public bool ContainsKey(string key)
        {
            var _r = NativeMethods.welder_map_str_csharp_cases_Point_contains(_h_MapStrPoint, key, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public Point this[string key]
        {
            get
            {
                IntPtr _r = NativeMethods.welder_map_str_csharp_cases_Point_get(_h_MapStrPoint, key, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Point(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_map_str_csharp_cases_Point_set(_h_MapStrPoint, key, @value._h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }
        public bool Remove(string key)
        {
            var _r = NativeMethods.welder_map_str_csharp_cases_Point_remove(_h_MapStrPoint, key, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public void Clear()
        {
            NativeMethods.welder_map_str_csharp_cases_Point_clear(_h_MapStrPoint, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }
        public void Dispose() => _h_MapStrPoint.Dispose();
    }

    internal sealed class UMapIntStrHandle : SafeHandle
    {
        internal UMapIntStrHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_umap_int_str_destroy(handle);
            return true;
        }
    }

    /// <summary>A reference-semantic C++ std::unordered_map of int to string.</summary>
    public sealed class UMapIntStr : IDisposable
    {
        internal UMapIntStrHandle _h_UMapIntStr;
        internal object? _owner;
        internal UMapIntStr(IntPtr handle, bool owns) { _h_UMapIntStr = new UMapIntStrHandle(handle, owns); }
        public UMapIntStr() : this(_New(), true) {}
        private static IntPtr _New()
        {
            IntPtr _r = NativeMethods.welder_umap_int_str_new(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public int Count
        {
            get
            {
                var _r = NativeMethods.welder_umap_int_str_size(_h_UMapIntStr, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return (int)_r;
            }
        }
        public bool ContainsKey(int key)
        {
            var _r = NativeMethods.welder_umap_int_str_contains(_h_UMapIntStr, key, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public string this[int key]
        {
            get
            {
                IntPtr _r = NativeMethods.welder_umap_int_str_get(_h_UMapIntStr, key, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
                finally { NativeMethods.welder_free(_r); }
            }
            set
            {
                NativeMethods.welder_umap_int_str_set(_h_UMapIntStr, key, @value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }
        public bool Remove(int key)
        {
            var _r = NativeMethods.welder_umap_int_str_remove(_h_UMapIntStr, key, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public void Clear()
        {
            NativeMethods.welder_umap_int_str_clear(_h_UMapIntStr, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }
        public void Dispose() => _h_UMapIntStr.Dispose();
    }

    internal sealed class ArrayPointx2Handle : SafeHandle
    {
        internal ArrayPointx2Handle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_arr2_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A reference-semantic C++ std::array of 2 Point (live element views; fixed size).</summary>
    public sealed class ArrayPointx2 : IDisposable
    {
        internal ArrayPointx2Handle _h_ArrayPointx2;
        internal object? _owner;
        internal ArrayPointx2(IntPtr handle, bool owns) { _h_ArrayPointx2 = new ArrayPointx2Handle(handle, owns); }
        public ArrayPointx2() : this(_New(), true) {}
        private static IntPtr _New()
        {
            IntPtr _r = NativeMethods.welder_arr2_csharp_cases_Point_new(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }
        public int Count => 2;
        public Point this[int i]
        {
            get
            {
                IntPtr _r = NativeMethods.welder_arr2_csharp_cases_Point_get(_h_ArrayPointx2, i, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                var _v = new Point(_r, false);
                _v._owner = this;
                return _v;
            }
            set
            {
                NativeMethods.welder_arr2_csharp_cases_Point_set(_h_ArrayPointx2, i, value._h_Point, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }
        public void Dispose() => _h_ArrayPointx2.Dispose();
    }

    internal sealed class PointSharedBox : SafeHandle
    {
        internal PointSharedBox(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_sp_csharp_cases_Point_free(handle);
            return true;
        }
    }

    public static class Global
    {
        public static Point? MakePoint(int x, int y)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_f_make_point_0(x, y, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            if (_r == IntPtr.Zero) return null;
            return new Point(_r, true);
        }

        public unsafe static (int, string) Tagged(int v)
        {
            var _r = NativeMethods.welder_csharp_cases_f_tagged_0(v, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            var _slots = (WelderOptWire*)_r.Data;
            var _t0 = unchecked((int)_slots[0].I);
            string _t1;
            {
                IntPtr _sp = _slots[1].S;
                try { _t1 = Marshal.PtrToStringUTF8(_sp) ?? ""; }
                finally { NativeMethods.welder_free(_sp); }
            }
            NativeMethods.welder_free(_r.Data);
            return (_t0, _t1);
        }

        public unsafe static long PairSum((int, long) p)
        {
            var _tw0 = stackalloc WelderOptWire[2];
            _tw0[0] = new WelderOptWire { Has = 1, I = (long)p.Item1 };
            _tw0[1] = new WelderOptWire { Has = 1, I = (long)p.Item2 };
            var _r = NativeMethods.welder_csharp_cases_f_pair_sum_0((IntPtr)_tw0, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public unsafe static (int, double, string, Point) Bundle()
        {
            var _r = NativeMethods.welder_csharp_cases_f_bundle_0(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            var _slots = (WelderOptWire*)_r.Data;
            var _t0 = unchecked((int)_slots[0].I);
            var _t1 = unchecked((double)_slots[1].F);
            string _t2;
            {
                IntPtr _sp = _slots[2].S;
                try { _t2 = Marshal.PtrToStringUTF8(_sp) ?? ""; }
                finally { NativeMethods.welder_free(_sp); }
            }
            var _t3 = new Point(_slots[3].P, true);
            NativeMethods.welder_free(_r.Data);
            return (_t0, _t1, _t2, _t3);
        }

        public static void Reject(int v)
        {
            NativeMethods.welder_csharp_cases_f_reject_0(v, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
        }

        /// <summary>Add two numbers.</summary>
        public static int Add(int a, int b)
        {
            var _r = NativeMethods.welder_csharp_cases_f_add_0(a, b, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public static string Greet(string name)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_f_greet_0(name, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

        public static int Answer
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_v_answer_get(out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_v_answer_set(@value, out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
            }
        }

        public static double Golden
        {
            get
            {
                var _r = NativeMethods.welder_csharp_cases_v_golden_get(out WelderError _e);
                WelderInterop.ThrowIfError(in _e);
                return _r;
            }
        }

        public static int AgeOf(Animal a)
        {
            var _r = NativeMethods.welder_csharp_cases_f_age_of_0(a._h_Animal, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public static Point? MaybePoint(bool give)
        {
            var _r = NativeMethods.welder_csharp_cases_f_maybe_point_0(give, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r.Has != 0 ? new Point(_r.P, true) : null;
        }

        public static Level? MaybeLevel(bool give)
        {
            var _r = NativeMethods.welder_csharp_cases_f_maybe_level_0(give, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r.Has != 0 ? (Level?)(Level)_r.I : null;
        }

        public static Point? SharedPoint(int x, int y)
        {
            var _r = NativeMethods.welder_csharp_cases_f_shared_point_0(x, y, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            if (_r.Obj == IntPtr.Zero) return null;
            var _v = new Point(_r.Obj, false);
            _v._owner = new PointSharedBox(_r.Box, true);
            return _v;
        }

        public static Point? NoPoint()
        {
            var _r = NativeMethods.welder_csharp_cases_f_no_point_0(out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            if (_r.Obj == IntPtr.Zero) return null;
            var _v = new Point(_r.Obj, false);
            _v._owner = new PointSharedBox(_r.Box, true);
            return _v;
        }

        public static int SharedX(Point? p)
        {
            var _r = NativeMethods.welder_csharp_cases_f_shared_x_0(p is null ? IntPtr.Zero : p._h_Point.DangerousGetHandle(), out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

        public static Point? UniquePoint(int x, int y)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_f_unique_point_0(x, y, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            if (_r == IntPtr.Zero) return null;
            return new Point(_r, true);
        }

        public static string DescribeShape(Shape s)
        {
            IntPtr _r = NativeMethods.welder_csharp_cases_f_describe_shape_0(s._h_Shape, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            try { return Marshal.PtrToStringUTF8(_r) ?? ""; }
            finally { NativeMethods.welder_free(_r); }
        }

    }

    namespace Inner
    {
    public static class Global
    {
        public static int Twice(int v)
        {
            var _r = NativeMethods.welder_csharp_cases_inner_f_twice_0(v, out WelderError _e);
            WelderInterop.ThrowIfError(in _e);
            return _r;
        }

    }

    }

}
