// <auto-generated> welder C#/.NET bindings. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace csharp_cases
{
    /// <summary>The native error slot every welder thunk fills (code 0 = success).</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderError
    {
        public int Code;
        public IntPtr Message;
    }

    /// <summary>A C++ exception that crossed the native boundary.</summary>
    public class WelderNativeException : Exception
    {
        public int NativeCode { get; }
        public WelderNativeException(int code, string message) : base(message)
        {
            NativeCode = code;
        }
    }

    /// <summary>The by-value wire of an optional with a leaf payload.</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderOptWire
    {
        public byte Has;
        public long I;
        public double F;
        public IntPtr S;
        public IntPtr P;
    }

    /// <summary>The by-value wire of a scalar/enum sequence (buffer + length).</summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct WelderSeqWire
    {
        public IntPtr Data;
        public long Len;
    }

    internal static class WelderInterop
    {
        internal static void ThrowIfError(in WelderError err)
        {
            if (err.Code == 0) return;
            string msg = "";
            if (err.Message != IntPtr.Zero)
            {
                msg = Marshal.PtrToStringUTF8(err.Message) ?? "";
                NativeMethods.welder_free(err.Message);
            }
            throw err.Code switch
            {
                2 => new OutOfMemoryException(msg),
                3 => new ArgumentException(msg),
                4 => new ArgumentOutOfRangeException(null, msg),
                5 => new ArithmeticException(msg),
                _ => (Exception)new WelderNativeException(err.Code, msg),
            };
        }
    }

    internal static partial class NativeMethods
    {
        internal const string Lib = "welder_test_csharp_native";

        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_new_1(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_clone(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_x(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_x(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_y(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_set_y(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_get_stamp(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_m_sum_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_offset_1(PointHandle self, int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_label_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial Color welder_csharp_cases_Point_m_hue_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_m_translated_0(PointHandle self, int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_s_origin_0(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_m_explode_0(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Point_pget_Depth(PointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Point_pset_Depth(PointHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Point_op_plus_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Point_op_equals_equals_b_0(PointHandle self, PointHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_new_agg(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Size_clone(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_width(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_width(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Size_get_height(SizeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Size_set_height(SizeHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Holder_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_clone(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_item_copy_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Holder_m_peek_0(HolderHandle self, [MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Holder_m_item_x_0(HolderHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_make_point_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_f_reject_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_new_1(PointHandle a0, PointHandle a1, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_clone(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_start(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_start(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Segment_get_end(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Segment_set_end(SegmentHandle self, PointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Segment_m_span_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] [return: MarshalAs(UnmanagedType.U1)] internal static partial bool welder_csharp_cases_Segment_m_degenerate_0(SegmentHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_add_0(int a0, int a1, out WelderError err);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_csharp_cases_f_greet_0(string a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_v_answer_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_v_answer_set(int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial double welder_csharp_cases_v_golden_get(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Animal_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_clone(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Animal_get_age(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Animal_set_age(AnimalHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Animal_m_kind_0(AnimalHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Legged_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Legged_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Legged_clone(LeggedHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Legged_get_legs(LeggedHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Legged_set_legs(LeggedHandle self, int v, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_as_csharp_cases_Animal(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_as_csharp_cases_Legged(IntPtr self);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Dog_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_clone(DogHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Dog_m_bark_0(DogHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_f_age_of_0(AnimalHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Basket_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Basket_clone(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_Basket_get_nums(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_set_nums(BasketHandle self, WelderSeqWire v, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_Basket_get_label(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_set_label(BasketHandle self, WelderOptWire v, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_Basket_m_find_0(BasketHandle self, int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial long welder_csharp_cases_Basket_m_total_0(BasketHandle self, WelderSeqWire a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderSeqWire welder_csharp_cases_Basket_m_triple_0(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Basket_m_set_triple_0(BasketHandle self, WelderSeqWire a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial double welder_csharp_cases_Basket_m_trip_sum_0(BasketHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_f_maybe_point_0([MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial WelderOptWire welder_csharp_cases_f_maybe_level_0([MarshalAs(UnmanagedType.U1)] bool a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Route_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_clone(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_vec_csharp_cases_Point_new(out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial long welder_vec_csharp_cases_Point_size(VectorPointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_vec_csharp_cases_Point_get(VectorPointHandle self, long i, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_set(VectorPointHandle self, long i, PointHandle elem, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_add(VectorPointHandle self, PointHandle elem, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_vec_csharp_cases_Point_clear(VectorPointHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_get_stops(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Route_set_stops(RouteHandle self, VectorPointHandle v, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Route_m_stop_count_0(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Route_m_reversed_0(RouteHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Route_m_total_x_0(RouteHandle self, VectorPointHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_dir_init(IntPtr release, IntPtr s0, IntPtr s1);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_dir_bind(IntPtr self, IntPtr ctx, ulong mask);
        [LibraryImport(Lib)] internal static partial void welder_csharp_cases_Shape_destroy(IntPtr self);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_new_default(out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_clone(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_name_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_name_0_base(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Shape_m_sides_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_Shape_m_sides_0_base(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_Shape_m_describe_0(ShapeHandle self, out WelderError err);
        [LibraryImport(Lib)] internal static partial IntPtr welder_csharp_cases_f_describe_shape_0(ShapeHandle a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial int welder_csharp_cases_inner_f_twice_0(int a0, out WelderError err);
        [LibraryImport(Lib)] internal static partial void welder_free(IntPtr p);
        [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)] internal static partial IntPtr welder_dup_utf8(string s);
    }

    /// <summary>Primary display colors.</summary>
    public enum Color : int
    {
        Red = 0,
        Green = 1,
        Blue = 2,
    }

    public enum Level : byte
    {
        Low = 1,
        High = 200,
    }

    internal sealed class PointHandle : SafeHandle
    {
        internal PointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A 2-D integer point.</summary>
    public class Point : IDisposable
    {
        internal PointHandle _h_Point;
        internal object? __owner;
        internal bool __isDirector;
        internal Point(IntPtr handle, bool owns) { _h_Point = new PointHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Point() : this(__New_default(), true) {}

        private static IntPtr __New_1(int x_, int y_)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_new_1(x_, y_, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Point(int x_, int y_) : this(__New_1(x_, y_), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Point Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_clone(_h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public int X
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_x(_h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_x(_h_Point, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Y
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_y(_h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_set_y(_h_Point, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Stamp
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_get_stamp(_h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
        }

        public int Sum()
        {
            var __r = NativeMethods.welder_csharp_cases_Point_m_sum_0(_h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public void Offset(int dx, int dy)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_0(_h_Point, dx, dy, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public void Offset(int d)
        {
            NativeMethods.welder_csharp_cases_Point_m_offset_1(_h_Point, d, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public string Label()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_m_label_0(_h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public Color Hue()
        {
            var __r = NativeMethods.welder_csharp_cases_Point_m_hue_0(_h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public Point Translated(int dx, int dy)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_m_translated_0(_h_Point, dx, dy, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public static Point Origin()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_s_origin_0(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public void Explode()
        {
            NativeMethods.welder_csharp_cases_Point_m_explode_0(_h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        public int Depth
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Point_pget_Depth(_h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Point_pset_Depth(_h_Point, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public static Point operator +(Point l, Point r)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Point_op_plus_b_0(l._h_Point, r._h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public static bool operator ==(Point? l, Point? r)
        {
            if (ReferenceEquals(l, r)) return true;
            if (l is null || r is null) return false;
            var __r = NativeMethods.welder_csharp_cases_Point_op_equals_equals_b_0(l._h_Point, r._h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public static bool operator !=(Point? l, Point? r) => !(l == r);

        public override bool Equals(object? obj) => obj is Point __o && this == __o;
        /// <summary>Reference-identity hash (the C++ type has no hash to mirror).</summary>
        public override int GetHashCode() => base.GetHashCode();

        public virtual void Dispose() => _h_Point.Dispose();
    }

    internal sealed class SizeHandle : SafeHandle
    {
        internal SizeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Size_destroy(handle);
            return true;
        }
    }

    public class Size : IDisposable
    {
        internal SizeHandle _h_Size;
        internal object? __owner;
        internal bool __isDirector;
        internal Size(IntPtr handle, bool owns) { _h_Size = new SizeHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Size() : this(__New_default(), true) {}

        private static IntPtr __New_agg(int width, int height)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_new_agg(width, height, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Size(int width, int height) : this(__New_agg(width, height), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Size Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Size_clone(_h_Size, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Size(__r, true);
        }

        public int Width
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Size_get_width(_h_Size, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_width(_h_Size, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Height
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Size_get_height(_h_Size, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Size_set_height(_h_Size, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public virtual void Dispose() => _h_Size.Dispose();
    }

    internal sealed class HolderHandle : SafeHandle
    {
        internal HolderHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Holder_destroy(handle);
            return true;
        }
    }

    public class Holder : IDisposable
    {
        internal HolderHandle _h_Holder;
        internal object? __owner;
        internal bool __isDirector;
        internal Holder(IntPtr handle, bool owns) { _h_Holder = new HolderHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Holder() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Holder Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_clone(_h_Holder, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Holder(__r, true);
        }

        public Point Item()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_item_0(_h_Holder, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            var __v = new Point(__r, false);
            __v.__owner = this;
            return __v;
        }

        public Point ItemCopy()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_item_copy_0(_h_Holder, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Point(__r, true);
        }

        public Point? Peek(bool give)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Holder_m_peek_0(_h_Holder, give, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            if (__r == IntPtr.Zero) return null;
            var __v = new Point(__r, false);
            return __v;
        }

        public int ItemX()
        {
            var __r = NativeMethods.welder_csharp_cases_Holder_m_item_x_0(_h_Holder, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public virtual void Dispose() => _h_Holder.Dispose();
    }

    internal sealed class SegmentHandle : SafeHandle
    {
        internal SegmentHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Segment_destroy(handle);
            return true;
        }
    }

    public class Segment : IDisposable
    {
        internal SegmentHandle _h_Segment;
        internal object? __owner;
        internal bool __isDirector;
        internal Segment(IntPtr handle, bool owns) { _h_Segment = new SegmentHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Segment() : this(__New_default(), true) {}

        private static IntPtr __New_1(Point a, Point b)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_new_1(a._h_Point, b._h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Segment(Point a, Point b) : this(__New_1(a, b), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Segment Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Segment_clone(_h_Segment, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Segment(__r, true);
        }

        public Point Start
        {
            get
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Segment_get_start(_h_Segment, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new Point(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_start(_h_Segment, @value._h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public Point End
        {
            get
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Segment_get_end(_h_Segment, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new Point(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Segment_set_end(_h_Segment, @value._h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int Span()
        {
            var __r = NativeMethods.welder_csharp_cases_Segment_m_span_0(_h_Segment, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public bool Degenerate()
        {
            var __r = NativeMethods.welder_csharp_cases_Segment_m_degenerate_0(_h_Segment, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public virtual void Dispose() => _h_Segment.Dispose();
    }

    internal sealed class AnimalHandle : SafeHandle
    {
        internal AnimalHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Animal_destroy(handle);
            return true;
        }
    }

    public class Animal : IDisposable
    {
        internal AnimalHandle _h_Animal;
        internal object? __owner;
        internal bool __isDirector;
        internal Animal(IntPtr handle, bool owns) { _h_Animal = new AnimalHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Animal_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Animal() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Animal Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Animal_clone(_h_Animal, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Animal(__r, true);
        }

        public int Age
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Animal_get_age(_h_Animal, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Animal_set_age(_h_Animal, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public string Kind()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Animal_m_kind_0(_h_Animal, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public virtual void Dispose() => _h_Animal.Dispose();
    }

    internal sealed class LeggedHandle : SafeHandle
    {
        internal LeggedHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Legged_destroy(handle);
            return true;
        }
    }

    public class Legged : IDisposable
    {
        internal LeggedHandle _h_Legged;
        internal object? __owner;
        internal bool __isDirector;
        internal Legged(IntPtr handle, bool owns) { _h_Legged = new LeggedHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Legged_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Legged() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Legged Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Legged_clone(_h_Legged, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Legged(__r, true);
        }

        public int Legs
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Legged_get_legs(_h_Legged, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Legged_set_legs(_h_Legged, @value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public virtual void Dispose() => _h_Legged.Dispose();
    }

    internal sealed class DogHandle : SafeHandle
    {
        internal DogHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Dog_destroy(handle);
            return true;
        }
    }

    public class Dog : Animal
    {
        internal DogHandle _h_Dog;
        internal Dog(IntPtr handle, bool owns) : base(NativeMethods.welder_csharp_cases_Dog_as_csharp_cases_Animal(handle), false) { _h_Dog = new DogHandle(handle, owns); }

        /// <summary>This object's Legged base surface (a non-owning view).</summary>
        public Legged AsLegged()
        {
            IntPtr __p = NativeMethods.welder_csharp_cases_Dog_as_csharp_cases_Legged(_h_Dog.DangerousGetHandle());
            GC.KeepAlive(this);
            var __v = new Legged(__p, false);
            __v.__owner = this;
            return __v;
        }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Dog_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Dog() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Dog Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Dog_clone(_h_Dog, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Dog(__r, true);
        }

        public string Bark()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Dog_m_bark_0(_h_Dog, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public override void Dispose() { _h_Dog.Dispose(); base.Dispose(); }
    }

    internal sealed class BasketHandle : SafeHandle
    {
        internal BasketHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Basket_destroy(handle);
            return true;
        }
    }

    public class Basket : IDisposable
    {
        internal BasketHandle _h_Basket;
        internal object? __owner;
        internal bool __isDirector;
        internal Basket(IntPtr handle, bool owns) { _h_Basket = new BasketHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Basket_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Basket() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Basket Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Basket_clone(_h_Basket, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Basket(__r, true);
        }

        public unsafe int[] Nums
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Basket_get_nums(_h_Basket, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __out = new int[__r.Len];
                if (__r.Len != 0)
                {
                    fixed (int* __d = __out)
                        Buffer.MemoryCopy((void*)__r.Data, __d, __r.Len * sizeof(int), __r.Len * sizeof(int));
                }
                if (__r.Data != IntPtr.Zero) NativeMethods.welder_free(__r.Data);
                return __out;
            }
            set
            {
                fixed (int* __pin0 = @value) {
                NativeMethods.welder_csharp_cases_Basket_set_nums(_h_Basket, new WelderSeqWire { Data = (IntPtr)__pin0, Len = @value.Length }, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                }
            }
        }

        public string? Label
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_Basket_get_label(_h_Basket, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                if (__r.Has == 0) return null;
                IntPtr __s = __r.S;
                try { return Marshal.PtrToStringUTF8(__s) ?? ""; }
                finally { NativeMethods.welder_free(__s); }
            }
            set
            {
                NativeMethods.welder_csharp_cases_Basket_set_label(_h_Basket, @value is null ? default : new WelderOptWire { Has = 1, S = NativeMethods.welder_dup_utf8(@value) }, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int? Find(int v)
        {
            var __r = NativeMethods.welder_csharp_cases_Basket_m_find_0(_h_Basket, v, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r.Has != 0 ? (int?)unchecked((int)__r.I) : null;
        }

        public unsafe long Total(int[] extra)
        {
            fixed (int* __pin0 = extra) {
            var __r = NativeMethods.welder_csharp_cases_Basket_m_total_0(_h_Basket, new WelderSeqWire { Data = (IntPtr)__pin0, Len = extra.Length }, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
            }
        }

        public unsafe double[] Triple()
        {
            var __r = NativeMethods.welder_csharp_cases_Basket_m_triple_0(_h_Basket, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            var __out = new double[__r.Len];
            if (__r.Len != 0)
            {
                fixed (double* __d = __out)
                    Buffer.MemoryCopy((void*)__r.Data, __d, __r.Len * sizeof(double), __r.Len * sizeof(double));
            }
            if (__r.Data != IntPtr.Zero) NativeMethods.welder_free(__r.Data);
            return __out;
        }

        public unsafe void SetTriple(double[] a)
        {
            fixed (double* __pin0 = a) {
            NativeMethods.welder_csharp_cases_Basket_m_set_triple_0(_h_Basket, new WelderSeqWire { Data = (IntPtr)__pin0, Len = a.Length }, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            }
        }

        public double TripSum()
        {
            var __r = NativeMethods.welder_csharp_cases_Basket_m_trip_sum_0(_h_Basket, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public virtual void Dispose() => _h_Basket.Dispose();
    }

    internal sealed class RouteHandle : SafeHandle
    {
        internal RouteHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Route_destroy(handle);
            return true;
        }
    }

    public class Route : IDisposable
    {
        internal RouteHandle _h_Route;
        internal object? __owner;
        internal bool __isDirector;
        internal Route(IntPtr handle, bool owns) { _h_Route = new RouteHandle(handle, owns); }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Route_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Route() : this(__New_default(), true) {}

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Route Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Route_clone(_h_Route, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Route(__r, true);
        }

        public VectorPoint Stops
        {
            get
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Route_get_stops(_h_Route, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new VectorPoint(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_csharp_cases_Route_set_stops(_h_Route, @value._h_VectorPoint, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public int StopCount()
        {
            var __r = NativeMethods.welder_csharp_cases_Route_m_stop_count_0(_h_Route, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public VectorPoint Reversed()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Route_m_reversed_0(_h_Route, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new VectorPoint(__r, true);
        }

        public int TotalX(VectorPoint pts)
        {
            var __r = NativeMethods.welder_csharp_cases_Route_m_total_x_0(_h_Route, pts._h_VectorPoint, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public virtual void Dispose() => _h_Route.Dispose();
    }

    internal sealed class ShapeHandle : SafeHandle
    {
        internal ShapeHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_csharp_cases_Shape_destroy(handle);
            return true;
        }
    }

    public class Shape : IDisposable
    {
        internal ShapeHandle _h_Shape;
        internal object? __owner;
        internal bool __isDirector;
        internal Shape(IntPtr handle, bool owns) { _h_Shape = new ShapeHandle(handle, owns); }

        private static bool __cbInit;
        private static unsafe void __EnsureCallbacks()
        {
            if (__cbInit) return;
            __cbInit = true;
            NativeMethods.welder_csharp_cases_Shape_dir_init(
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&__Release,
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, WelderError*, IntPtr>)&__Slot0,
                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, WelderError*, int>)&__Slot1);
        }
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static void __Release(IntPtr ctx) => GCHandle.FromIntPtr(ctx).Free();
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static unsafe IntPtr __Slot0(IntPtr __ctx, WelderError* __err)
        {
            try
            {
                var __self = (Shape?)GCHandle.FromIntPtr(__ctx).Target;
                if (__self is null) throw new InvalidOperationException("welder: director target collected");
                return NativeMethods.welder_dup_utf8(__self.Name());
            }
            catch (Exception __ex)
            {
                __err->Code = 7;
                __err->Message = NativeMethods.welder_dup_utf8(__ex.Message);
                return default;
            }
        }
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
        private static unsafe int __Slot1(IntPtr __ctx, WelderError* __err)
        {
            try
            {
                var __self = (Shape?)GCHandle.FromIntPtr(__ctx).Target;
                if (__self is null) throw new InvalidOperationException("welder: director target collected");
                return __self.Sides();
            }
            catch (Exception __ex)
            {
                __err->Code = 7;
                __err->Message = NativeMethods.welder_dup_utf8(__ex.Message);
                return default;
            }
        }
        private static ulong __OverrideMask(Type __t)
        {
            ulong __m = 0;
            if (__t == typeof(Shape)) return __m;
            if (__NotWrapper(__t.GetMethod("Name", new Type[] {  })?.DeclaringType)) __m |= 1UL << 0;
            if (__NotWrapper(__t.GetMethod("Sides", new Type[] {  })?.DeclaringType)) __m |= 1UL << 1;
            return __m;
        }
        private static bool __NotWrapper(Type? __d) =>
            __d is not null && __d != typeof(Shape);
        private void __DirBind()
        {
            __isDirector = true;
            __EnsureCallbacks();
            NativeMethods.welder_csharp_cases_Shape_dir_bind(
                _h_Shape.DangerousGetHandle(),
                GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)),
                __OverrideMask(GetType()));
            GC.KeepAlive(this);
        }

        private static IntPtr __New_default()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Shape_new_default(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public Shape() : this(__New_default(), true) { __DirBind(); }

        /// <summary>Copy this instance (the C++ copy constructor).</summary>
        public Shape Clone()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Shape_clone(_h_Shape, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return new Shape(__r, true);
        }

        public virtual string Name()
        {
            if (__isDirector)
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Shape_m_name_0_base(_h_Shape, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
                finally { NativeMethods.welder_free(__r); }
            }
            else
            {
                IntPtr __r = NativeMethods.welder_csharp_cases_Shape_m_name_0(_h_Shape, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
                finally { NativeMethods.welder_free(__r); }
            }
        }

        public virtual int Sides()
        {
            if (__isDirector)
            {
                var __r = NativeMethods.welder_csharp_cases_Shape_m_sides_0_base(_h_Shape, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            else
            {
                var __r = NativeMethods.welder_csharp_cases_Shape_m_sides_0(_h_Shape, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
        }

        public string Describe()
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_Shape_m_describe_0(_h_Shape, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public virtual void Dispose() => _h_Shape.Dispose();
    }

    internal sealed class VectorPointHandle : SafeHandle
    {
        internal VectorPointHandle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)
        {
            SetHandle(handle);
        }
        public override bool IsInvalid => handle == IntPtr.Zero;
        protected override bool ReleaseHandle()
        {
            NativeMethods.welder_vec_csharp_cases_Point_destroy(handle);
            return true;
        }
    }

    /// <summary>A reference-semantic C++ vector of Point (live element views).</summary>
    public sealed class VectorPoint : IDisposable
    {
        internal VectorPointHandle _h_VectorPoint;
        internal object? __owner;
        internal VectorPoint(IntPtr handle, bool owns) { _h_VectorPoint = new VectorPointHandle(handle, owns); }
        public VectorPoint() : this(__New(), true) {}
        private static IntPtr __New()
        {
            IntPtr __r = NativeMethods.welder_vec_csharp_cases_Point_new(out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }
        public int Count
        {
            get
            {
                var __r = NativeMethods.welder_vec_csharp_cases_Point_size(_h_VectorPoint, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return (int)__r;
            }
        }
        public Point this[int i]
        {
            get
            {
                IntPtr __r = NativeMethods.welder_vec_csharp_cases_Point_get(_h_VectorPoint, i, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                var __v = new Point(__r, false);
                __v.__owner = this;
                return __v;
            }
            set
            {
                NativeMethods.welder_vec_csharp_cases_Point_set(_h_VectorPoint, i, value._h_Point, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }
        public void Add(Point item)
        {
            NativeMethods.welder_vec_csharp_cases_Point_add(_h_VectorPoint, item._h_Point, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }
        public void Clear()
        {
            NativeMethods.welder_vec_csharp_cases_Point_clear(_h_VectorPoint, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }
        public void Dispose() => _h_VectorPoint.Dispose();
    }

    public static class Global
    {
        public static Point? MakePoint(int x, int y)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_f_make_point_0(x, y, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            if (__r == IntPtr.Zero) return null;
            return new Point(__r, true);
        }

        public static void Reject(int v)
        {
            NativeMethods.welder_csharp_cases_f_reject_0(v, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
        }

        /// <summary>Add two numbers.</summary>
        public static int Add(int a, int b)
        {
            var __r = NativeMethods.welder_csharp_cases_f_add_0(a, b, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public static string Greet(string name)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_f_greet_0(name, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

        public static int Answer
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_v_answer_get(out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
            set
            {
                NativeMethods.welder_csharp_cases_v_answer_set(@value, out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
            }
        }

        public static double Golden
        {
            get
            {
                var __r = NativeMethods.welder_csharp_cases_v_golden_get(out WelderError __e);
                WelderInterop.ThrowIfError(in __e);
                return __r;
            }
        }

        public static int AgeOf(Animal a)
        {
            var __r = NativeMethods.welder_csharp_cases_f_age_of_0(a._h_Animal, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

        public static Point? MaybePoint(bool give)
        {
            var __r = NativeMethods.welder_csharp_cases_f_maybe_point_0(give, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r.Has != 0 ? new Point(__r.P, true) : null;
        }

        public static Level? MaybeLevel(bool give)
        {
            var __r = NativeMethods.welder_csharp_cases_f_maybe_level_0(give, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r.Has != 0 ? (Level?)(Level)__r.I : null;
        }

        public static string DescribeShape(Shape s)
        {
            IntPtr __r = NativeMethods.welder_csharp_cases_f_describe_shape_0(s._h_Shape, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            try { return Marshal.PtrToStringUTF8(__r) ?? ""; }
            finally { NativeMethods.welder_free(__r); }
        }

    }

    public static class Inner
    {
        public static int Twice(int v)
        {
            var __r = NativeMethods.welder_csharp_cases_inner_f_twice_0(v, out WelderError __e);
            WelderInterop.ThrowIfError(in __e);
            return __r;
        }

    }

}
