// <auto-generated> welder C#/.NET native shim. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
// Compiled with reflection against the same welded header the
// generator saw: thunk bodies SPLICE the exact member reflection
// (re-derived by the shared lookup layer), so no C++ type is
// respelled here - only the C-ABI wire types are text.
#include <cstdint>
#include <welder/vocabulary.hpp>
#include "cases.hpp"
#include <welder/rods/csharp/shim_support.hpp>

namespace wcs = ::welder::rods::csharp;

extern "C" {

void welder_csharp_cases_Point_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Point>(self); }

void* welder_csharp_cases_Point_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Point>(err); }

void* welder_csharp_cases_Point_new_1(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Point, wcs::ctor_at(^^::csharp_cases::Point, 1)>(err, a0, a1); }

void* welder_csharp_cases_Point_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Point>(self, err); }

std::int32_t welder_csharp_cases_Point_get_x(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "x")>(self, err); }

void welder_csharp_cases_Point_set_x(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "x")>(self, err, v); }

std::int32_t welder_csharp_cases_Point_get_y(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "y")>(self, err); }

void welder_csharp_cases_Point_set_y(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "y")>(self, err, v); }

std::int32_t welder_csharp_cases_Point_get_stamp(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "stamp")>(self, err); }

std::int32_t welder_csharp_cases_Point_m_sum_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "sum", 0)>(self, err); }

void welder_csharp_cases_Point_m_offset_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 0)>(self, err, a0, a1); }

void welder_csharp_cases_Point_m_offset_1(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 1)>(self, err, a0); }

const char* welder_csharp_cases_Point_m_label_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "label", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_m_hue_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "hue", 0)>(self, err); }

void* welder_csharp_cases_Point_m_translated_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "translated", 0)>(self, err, a0, a1); }

void* welder_csharp_cases_Point_s_origin_0(welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::Point, "origin", 0)>(err); }

void welder_csharp_cases_Point_m_explode_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "explode", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_pget_Depth(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 0)>(self, err); }

void welder_csharp_cases_Point_pset_Depth(void* self, std::int32_t v, welder_error* err) { (void)wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 1)>(self, err, v); }

void welder_csharp_cases_Size_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Size>(self); }

void* welder_csharp_cases_Size_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Size>(err); }

void* welder_csharp_cases_Size_new_agg(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::aggregate_construct<^^::csharp_cases::Size>(err, a0, a1); }

void* welder_csharp_cases_Size_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Size>(self, err); }

std::int32_t welder_csharp_cases_Size_get_width(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "width")>(self, err); }

void welder_csharp_cases_Size_set_width(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "width")>(self, err, v); }

std::int32_t welder_csharp_cases_Size_get_height(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "height")>(self, err); }

void welder_csharp_cases_Size_set_height(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "height")>(self, err, v); }

void welder_csharp_cases_Segment_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Segment>(self); }

void* welder_csharp_cases_Segment_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Segment>(err); }

void* welder_csharp_cases_Segment_new_1(void* a0, void* a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Segment, wcs::ctor_at(^^::csharp_cases::Segment, 1)>(err, a0, a1); }

void* welder_csharp_cases_Segment_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Segment>(self, err); }

void* welder_csharp_cases_Segment_get_start(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "start")>(self, err); }

void welder_csharp_cases_Segment_set_start(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "start")>(self, err, v); }

void* welder_csharp_cases_Segment_get_end(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "end")>(self, err); }

void welder_csharp_cases_Segment_set_end(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "end")>(self, err, v); }

std::int32_t welder_csharp_cases_Segment_m_span_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "span", 0)>(self, err); }

bool welder_csharp_cases_Segment_m_degenerate_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "degenerate", 0)>(self, err); }

std::int32_t welder_csharp_cases_f_add_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "add", 0)>(err, a0, a1); }

const char* welder_csharp_cases_f_greet_0(const char* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "greet", 0)>(err, a0); }

std::int32_t welder_csharp_cases_v_answer_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "answer")>(err); }

void welder_csharp_cases_v_answer_set(std::int32_t v, welder_error* err) { return wcs::shim::var_set<wcs::named_field(^^::csharp_cases, "answer")>(err, v); }

double welder_csharp_cases_v_golden_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "golden")>(err); }

std::int32_t welder_csharp_cases_inner_f_twice_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::inner, "twice", 0)>(err, a0); }

void welder_free(void* p) { std::free(p); }

} // extern "C"
