// <auto-generated> welder C#/.NET native shim. Do not edit -
// regenerate via the welder_csharp_generate_bindings() target.
// Compiled with reflection against the same welded header the
// generator saw: thunk bodies SPLICE the exact member reflection
// (re-derived by the shared lookup layer), so no C++ type is
// respelled here - only the C-ABI wire types are text.
#include <cstdint>
#include <welder/vocabulary.hpp>
#include "cases.hpp"
#include <welder/rods/csharp/shim_support.hpp>

namespace wcs = ::welder::rods::csharp;

struct __wcs_dir_csharp_cases_Shape final : ::csharp_cases::Shape {
    using ::csharp_cases::Shape::Shape;
    void* __wcs_ctx{nullptr};
    std::uint64_t __wcs_mask{0};
    struct __wcs_table_t {
        void (*release)(void*);
        const char* (*s0)(void*, welder_error*);
        std::int32_t (*s1)(void*, welder_error*);
    };
    static inline __wcs_table_t __wcs_tbl{};
    ~__wcs_dir_csharp_cases_Shape() override { if (__wcs_ctx && __wcs_tbl.release) __wcs_tbl.release(__wcs_ctx); }
    [: ::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0)) :] name() const override {
        if (__wcs_ctx && (__wcs_mask & (1ull << 0)) && __wcs_tbl.s0) {
            welder_error __e{0, nullptr};
            auto __r = __wcs_tbl.s0(__wcs_ctx, &__e);
            if (__e.code != 0) wcs::shim::rethrow_managed(&__e);
            return wcs::shim::from_wire_return<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0))>(__r);
        }
        return ::csharp_cases::Shape::name();
    }
    [: ::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1)) :] sides() const override {
        if (__wcs_ctx && (__wcs_mask & (1ull << 1)) && __wcs_tbl.s1) {
            welder_error __e{0, nullptr};
            auto __r = __wcs_tbl.s1(__wcs_ctx, &__e);
            if (__e.code != 0) wcs::shim::rethrow_managed(&__e);
            return wcs::shim::from_wire_return<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1))>(__r);
        }
        return ::csharp_cases::Shape::sides();
    }
};

extern "C" {

void welder_csharp_cases_Point_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Point>(self); }

void* welder_csharp_cases_Point_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Point>(err); }

void* welder_csharp_cases_Point_new_1(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Point, wcs::ctor_at(^^::csharp_cases::Point, 1)>(err, a0, a1); }

void* welder_csharp_cases_Point_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Point>(self, err); }

std::int32_t welder_csharp_cases_Point_get_x(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "x")>(self, err); }

void welder_csharp_cases_Point_set_x(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "x")>(self, err, v); }

std::int32_t welder_csharp_cases_Point_get_y(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "y")>(self, err); }

void welder_csharp_cases_Point_set_y(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "y")>(self, err, v); }

std::int32_t welder_csharp_cases_Point_get_stamp(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Point, wcs::named_field(^^::csharp_cases::Point, "stamp")>(self, err); }

std::int32_t welder_csharp_cases_Point_m_sum_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "sum", 0)>(self, err); }

void welder_csharp_cases_Point_m_offset_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 0)>(self, err, a0, a1); }

void welder_csharp_cases_Point_m_offset_1(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "offset", 1)>(self, err, a0); }

const char* welder_csharp_cases_Point_m_label_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "label", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_m_hue_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "hue", 0)>(self, err); }

void* welder_csharp_cases_Point_m_translated_0(void* self, std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "translated", 0)>(self, err, a0, a1); }

void* welder_csharp_cases_Point_s_origin_0(welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::Point, "origin", 0)>(err); }

void welder_csharp_cases_Point_m_explode_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "explode", 0)>(self, err); }

std::int32_t welder_csharp_cases_Point_pget_Depth(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 0)>(self, err); }

void welder_csharp_cases_Point_pset_Depth(void* self, std::int32_t v, welder_error* err) { (void)wcs::shim::method<^^::csharp_cases::Point, wcs::named_member(^^::csharp_cases::Point, "depth", 1)>(self, err, v); }

void* welder_csharp_cases_Point_op_plus_b_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_operator(^^::csharp_cases::Point, std::meta::operators::op_plus, false, 0)>(self, err, a0); }

bool welder_csharp_cases_Point_op_equals_equals_b_0(void* self, void* a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Point, wcs::named_operator(^^::csharp_cases::Point, std::meta::operators::op_equals_equals, false, 0)>(self, err, a0); }

void welder_csharp_cases_Size_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Size>(self); }

void* welder_csharp_cases_Size_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Size>(err); }

void* welder_csharp_cases_Size_new_agg(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::aggregate_construct<^^::csharp_cases::Size>(err, a0, a1); }

void* welder_csharp_cases_Size_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Size>(self, err); }

std::int32_t welder_csharp_cases_Size_get_width(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "width")>(self, err); }

void welder_csharp_cases_Size_set_width(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "width")>(self, err, v); }

std::int32_t welder_csharp_cases_Size_get_height(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "height")>(self, err); }

void welder_csharp_cases_Size_set_height(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Size, wcs::named_field(^^::csharp_cases::Size, "height")>(self, err, v); }

void welder_csharp_cases_Holder_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Holder>(self); }

void* welder_csharp_cases_Holder_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Holder>(err); }

void* welder_csharp_cases_Holder_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Holder>(self, err); }

void* welder_csharp_cases_Holder_m_item_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item", 0)>(self, err); }

void* welder_csharp_cases_Holder_m_item_copy_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item_copy", 0)>(self, err); }

void* welder_csharp_cases_Holder_m_peek_0(void* self, bool a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "peek", 0)>(self, err, a0); }

std::int32_t welder_csharp_cases_Holder_m_item_x_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Holder, wcs::named_member(^^::csharp_cases::Holder, "item_x", 0)>(self, err); }

void* welder_csharp_cases_f_make_point_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "make_point", 0)>(err, a0, a1); }

void welder_csharp_cases_f_reject_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "reject", 0)>(err, a0); }

void welder_csharp_cases_Segment_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Segment>(self); }

void* welder_csharp_cases_Segment_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Segment>(err); }

void* welder_csharp_cases_Segment_new_1(void* a0, void* a1, welder_error* err) { return wcs::shim::construct<^^::csharp_cases::Segment, wcs::ctor_at(^^::csharp_cases::Segment, 1)>(err, a0, a1); }

void* welder_csharp_cases_Segment_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Segment>(self, err); }

void* welder_csharp_cases_Segment_get_start(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "start")>(self, err); }

void welder_csharp_cases_Segment_set_start(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "start")>(self, err, v); }

void* welder_csharp_cases_Segment_get_end(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "end")>(self, err); }

void welder_csharp_cases_Segment_set_end(void* self, void* v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Segment, wcs::named_field(^^::csharp_cases::Segment, "end")>(self, err, v); }

std::int32_t welder_csharp_cases_Segment_m_span_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "span", 0)>(self, err); }

bool welder_csharp_cases_Segment_m_degenerate_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Segment, wcs::named_member(^^::csharp_cases::Segment, "degenerate", 0)>(self, err); }

std::int32_t welder_csharp_cases_f_add_0(std::int32_t a0, std::int32_t a1, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "add", 0)>(err, a0, a1); }

const char* welder_csharp_cases_f_greet_0(const char* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "greet", 0)>(err, a0); }

std::int32_t welder_csharp_cases_v_answer_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "answer")>(err); }

void welder_csharp_cases_v_answer_set(std::int32_t v, welder_error* err) { return wcs::shim::var_set<wcs::named_field(^^::csharp_cases, "answer")>(err, v); }

double welder_csharp_cases_v_golden_get(welder_error* err) { return wcs::shim::var_get<wcs::named_field(^^::csharp_cases, "golden")>(err); }

void welder_csharp_cases_Animal_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Animal>(self); }

void* welder_csharp_cases_Animal_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Animal>(err); }

void* welder_csharp_cases_Animal_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Animal>(self, err); }

std::int32_t welder_csharp_cases_Animal_get_age(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Animal, wcs::named_field(^^::csharp_cases::Animal, "age")>(self, err); }

void welder_csharp_cases_Animal_set_age(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Animal, wcs::named_field(^^::csharp_cases::Animal, "age")>(self, err, v); }

const char* welder_csharp_cases_Animal_m_kind_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Animal, wcs::named_member(^^::csharp_cases::Animal, "kind", 0)>(self, err); }

void welder_csharp_cases_Legged_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Legged>(self); }

void* welder_csharp_cases_Legged_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Legged>(err); }

void* welder_csharp_cases_Legged_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Legged>(self, err); }

std::int32_t welder_csharp_cases_Legged_get_legs(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Legged, wcs::named_field(^^::csharp_cases::Legged, "legs")>(self, err); }

void welder_csharp_cases_Legged_set_legs(void* self, std::int32_t v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Legged, wcs::named_field(^^::csharp_cases::Legged, "legs")>(self, err, v); }

void* welder_csharp_cases_Dog_as_csharp_cases_Animal(void* self) { return wcs::shim::upcast<^^::csharp_cases::Dog, ^^::csharp_cases::Animal>(self); }

void* welder_csharp_cases_Dog_as_csharp_cases_Legged(void* self) { return wcs::shim::upcast<^^::csharp_cases::Dog, ^^::csharp_cases::Legged>(self); }

void welder_csharp_cases_Dog_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Dog>(self); }

void* welder_csharp_cases_Dog_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Dog>(err); }

void* welder_csharp_cases_Dog_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Dog>(self, err); }

const char* welder_csharp_cases_Dog_m_bark_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Dog, wcs::named_member(^^::csharp_cases::Dog, "bark", 0)>(self, err); }

std::int32_t welder_csharp_cases_f_age_of_0(void* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "age_of", 0)>(err, a0); }

void welder_csharp_cases_Basket_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Basket>(self); }

void* welder_csharp_cases_Basket_new_default(welder_error* err) { return wcs::shim::default_construct<^^::csharp_cases::Basket>(err); }

void* welder_csharp_cases_Basket_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Basket>(self, err); }

welder_seq_wire welder_csharp_cases_Basket_get_nums(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "nums")>(self, err); }

void welder_csharp_cases_Basket_set_nums(void* self, welder_seq_wire v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "nums")>(self, err, v); }

welder_opt_wire welder_csharp_cases_Basket_get_label(void* self, welder_error* err) { return wcs::shim::field_get<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "label")>(self, err); }

void welder_csharp_cases_Basket_set_label(void* self, welder_opt_wire v, welder_error* err) { return wcs::shim::field_set<^^::csharp_cases::Basket, wcs::named_field(^^::csharp_cases::Basket, "label")>(self, err, v); }

welder_opt_wire welder_csharp_cases_Basket_m_find_0(void* self, std::int32_t a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "find", 0)>(self, err, a0); }

std::int64_t welder_csharp_cases_Basket_m_total_0(void* self, welder_seq_wire a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "total", 0)>(self, err, a0); }

welder_seq_wire welder_csharp_cases_Basket_m_triple_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "triple", 0)>(self, err); }

void welder_csharp_cases_Basket_m_set_triple_0(void* self, welder_seq_wire a0, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "set_triple", 0)>(self, err, a0); }

double welder_csharp_cases_Basket_m_trip_sum_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Basket, wcs::named_member(^^::csharp_cases::Basket, "trip_sum", 0)>(self, err); }

welder_opt_wire welder_csharp_cases_f_maybe_point_0(bool a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "maybe_point", 0)>(err, a0); }

welder_opt_wire welder_csharp_cases_f_maybe_level_0(bool a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "maybe_level", 0)>(err, a0); }

void welder_csharp_cases_Shape_dir_init(void* release, void* s0, void* s1) {
    __wcs_dir_csharp_cases_Shape::__wcs_tbl.release = reinterpret_cast<void (*)(void*)>(release);
    __wcs_dir_csharp_cases_Shape::__wcs_tbl.s0 = reinterpret_cast<const char* (*)(void*, welder_error*)>(s0);
    __wcs_dir_csharp_cases_Shape::__wcs_tbl.s1 = reinterpret_cast<std::int32_t (*)(void*, welder_error*)>(s1);
}

void welder_csharp_cases_Shape_dir_bind(void* self, void* ctx, std::uint64_t mask) {
    if (auto* __d = dynamic_cast<__wcs_dir_csharp_cases_Shape*>(reinterpret_cast<::csharp_cases::Shape*>(self))) { __d->__wcs_ctx = ctx; __d->__wcs_mask = mask; }
}

void welder_csharp_cases_Shape_destroy(void* self) { wcs::shim::destroy<^^::csharp_cases::Shape>(self); }

void* welder_csharp_cases_Shape_new_default(welder_error* err) { return wcs::shim::default_construct_as<^^__wcs_dir_csharp_cases_Shape, ^^::csharp_cases::Shape>(err); }

void* welder_csharp_cases_Shape_clone(void* self, welder_error* err) { return wcs::shim::clone<^^::csharp_cases::Shape>(self, err); }

const char* welder_csharp_cases_Shape_m_name_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "name", 0)>(self, err); }

const char* welder_csharp_cases_Shape_m_name_0_base(void* self, welder_error* err) {
    auto* __o = reinterpret_cast<::csharp_cases::Shape*>(self);
    return wcs::shim::guarded<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 0))>(err, [&]() -> decltype(auto) { return __o->::csharp_cases::Shape::name(); });
}

std::int32_t welder_csharp_cases_Shape_m_sides_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "sides", 0)>(self, err); }

std::int32_t welder_csharp_cases_Shape_m_sides_0_base(void* self, welder_error* err) {
    auto* __o = reinterpret_cast<::csharp_cases::Shape*>(self);
    return wcs::shim::guarded<::std::meta::return_type_of(wcs::director_slot(^^::csharp_cases::Shape, 1))>(err, [&]() -> decltype(auto) { return __o->::csharp_cases::Shape::sides(); });
}

const char* welder_csharp_cases_Shape_m_describe_0(void* self, welder_error* err) { return wcs::shim::method<^^::csharp_cases::Shape, wcs::named_member(^^::csharp_cases::Shape, "describe", 0)>(self, err); }

const char* welder_csharp_cases_f_describe_shape_0(void* a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases, "describe_shape", 0)>(err, a0); }

std::int32_t welder_csharp_cases_inner_f_twice_0(std::int32_t a0, welder_error* err) { return wcs::shim::function<wcs::named_member(^^::csharp_cases::inner, "twice", 0)>(err, a0); }

void welder_free(void* p) { std::free(p); }

const char* welder_dup_utf8(const char* s) { return wcs::shim::dup(s ? s : ""); }

} // extern "C"
