#pragma once
#include <cstddef>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <welder/rods/csharp/type_map.hpp> // emit_doc_comment / one_line

/** @file
    The C#/.NET backend's document assembler: the two-stream document and the RAII
    writer handles the driver's module/class/enum handles deduce to.

    The C# rod is the one backend that emits **two coordinated artifacts** from a
    single driver pass: a native `extern "C"` **shim** (`shim.cpp`, compiled into a
    shared library with reflection enabled, against the same welded header) and a
    managed **C# wrapper** (`Bindings.cs`, `[LibraryImport]` P/Invoke declarations
    + idiomatic classes). So @ref document holds several buffers rather than
    luacats' one, and @ref document::render_shim / @ref document::render_cs
    assemble the two files. Every emission primitive appends the paired native
    thunk and managed declaration together, keyed by the same symbol, so the two
    sides cannot desync; a duplicate symbol is caught at render time.

    The managed scaffolding rendered once per `Bindings.cs`:
    - `WelderError` — the blittable mirror of the shim's trailing error out-param;
    - `WelderInterop.ThrowIfError` — reads the slot, frees the message, throws
      @c WelderNativeException;
    - one `SafeHandle` subclass per welded class (its `ReleaseHandle` calls the
      class's destroy thunk), giving every wrapper finalizer-safe ownership and
      premature-collection safety on every P/Invoke that passes it.
*/

namespace welder::inline v0::rods::csharp {

/** Knobs the generator supplies once for the whole module. */
struct options {
    std::string cs_namespace{}; /**< The root C# namespace (the module name). */
    std::string library{};      /**< The P/Invoke library (the shared-lib base name). */
    std::string shim_include{}; /**< The header the shim `#include`s to see the types. */
};

/** A C# `static class` collecting one C++ namespace's free functions and variables
    (welded *types* are emitted flat in the module namespace in v1). */
struct static_class {
    std::string name{}; /**< The C# static-class name (the namespace identifier). */
    std::string body{}; /**< Accumulated static members. */
};

/** The growing pair of documents shared by every writer handle: the native shim and
    the managed wrapper. Class/enum text lands in @ref types; free functions and
    namespace variables land in a per-namespace @ref static_class; every P/Invoke
    declaration lands in @ref pinvoke (one `NativeMethods` class); every native thunk
    lands in @ref shim. */
struct document {
    options opts{};
    std::string module_doc{}; /**< The root namespace's doc (a file-header comment). */
    std::string shim{};    /**< `extern "C"` thunk bodies. */
    std::string pinvoke{}; /**< `[LibraryImport]` declarations (inside NativeMethods). */
    std::string types{};   /**< Wrapper class + enum declarations (flat in the ns). */
    std::vector<static_class> statics{}; /**< Per-namespace function/variable holders. */
    std::vector<std::string> symbols{};  /**< Every emitted C symbol (collision check). */

    /** Record an emitted C symbol; a duplicate aborts the generator with a
        designed message (two members whose underscore paths collide — e.g.
        `a_b::c` vs `a::b_c` — would silently link to one thunk otherwise). */
    void record_symbol(std::string sym) {
        for (const auto& s : symbols)
            if (s == sym) {
                shim += "#error welder: duplicate C symbol '" + sym +
                        "' (colliding underscore paths); rename one entity with "
                        "weld_as\n";
                return;
            }
        symbols.push_back(std::move(sym));
    }

    /** The accumulation buffer for the free functions/variables of the C# static
        class named @a name (created on first use).
        @param name the static-class name.
        @return a reference to its members buffer. */
    std::string& static_body(std::string_view name) {
        for (auto& s : statics)
            if (s.name == name)
                return s.body;
        statics.push_back({std::string{name}, {}});
        return statics.back().body;
    }

    /** The finished `shim.cpp` text. */
    std::string render_shim() const {
        std::string out{
            "// <auto-generated> welder C#/.NET native shim. Do not edit -\n"
            "// regenerate via the welder_csharp_generate_bindings() target.\n"
            "// Compiled with reflection against the same welded header the\n"
            "// generator saw: thunk bodies SPLICE the exact member reflection\n"
            "// (re-derived by the shared lookup layer), so no C++ type is\n"
            "// respelled here - only the C-ABI wire types are text.\n"
            "#include <cstdint>\n"
            "#include <welder/vocabulary.hpp>\n"};
        if (!opts.shim_include.empty())
            out += "#include \"" + opts.shim_include + "\"\n";
        out += "#include <welder/rods/csharp/shim_support.hpp>\n"
               "\n"
               "namespace wcs = ::welder::rods::csharp;\n"
               "\n"
               "extern \"C\" {\n\n";
        out += shim;
        out += "void welder_free(void* p) { std::free(p); }\n\n";
        out += "} // extern \"C\"\n";
        return out;
    }

    /** The finished `Bindings.cs` text. */
    std::string render_cs() const {
        std::string out{
            "// <auto-generated> welder C#/.NET bindings. Do not edit -\n"
            "// regenerate via the welder_csharp_generate_bindings() target.\n"};
        if (!module_doc.empty()) {
            out += "//\n";
            for (std::size_t b{0}; b < module_doc.size();) {
                std::size_t e{module_doc.find('\n', b)};
                if (e == std::string::npos)
                    e = module_doc.size();
                out += "// " + module_doc.substr(b, e - b) + "\n";
                b = e + 1;
            }
        }
        out += "using System;\nusing System.Runtime.InteropServices;\n\n";
        out += "namespace " + opts.cs_namespace + "\n{\n";
        // The error contract: the blittable slot + the check-and-throw helper.
        out +=
            "    /// <summary>The native error slot every welder thunk fills "
            "(code 0 = success).</summary>\n"
            "    [StructLayout(LayoutKind.Sequential)]\n"
            "    internal struct WelderError\n    {\n"
            "        public int Code;\n"
            "        public IntPtr Message;\n"
            "    }\n\n"
            "    /// <summary>A C++ exception that crossed the native "
            "boundary.</summary>\n"
            "    public class WelderNativeException : Exception\n    {\n"
            "        public int NativeCode { get; }\n"
            "        public WelderNativeException(int code, string message) : "
            "base(message)\n"
            "        {\n            NativeCode = code;\n        }\n"
            "    }\n\n"
            "    internal static class WelderInterop\n    {\n"
            "        internal static void ThrowIfError(in WelderError err)\n"
            "        {\n"
            "            if (err.Code == 0) return;\n"
            "            string msg = \"\";\n"
            "            if (err.Message != IntPtr.Zero)\n"
            "            {\n"
            "                msg = Marshal.PtrToStringUTF8(err.Message) ?? "
            "\"\";\n"
            "                NativeMethods.welder_free(err.Message);\n"
            "            }\n"
            "            throw new WelderNativeException(err.Code, msg);\n"
            "        }\n"
            "    }\n\n";
        // The P/Invoke surface: one partial static class (LibraryImport needs partial).
        out += "    internal static partial class NativeMethods\n    {\n";
        out += "        internal const string Lib = \"" + opts.library + "\";\n\n";
        out += pinvoke;
        out += "        [LibraryImport(Lib)] internal static partial void "
               "welder_free(IntPtr p);\n";
        out += "    }\n\n";
        out += types;
        for (const auto& s : statics) {
            out += "    public static class " + s.name + "\n    {\n";
            out += s.body;
            out += "    }\n\n";
        }
        out += "}\n";
        return out;
    }
};

/** A module handle: the shared document plus the C# static-class name that this
    namespace's free functions/variables accumulate into. Copyable (the driver's
    `add_submodule` returns one by value). */
struct module_writer {
    document* doc{nullptr};
    std::string cs_class{}; /**< This namespace's C# static-class name. */
};

/** A class handle. Accumulates the wrapper class body (properties, methods,
    constructors) and flushes the assembled `SafeHandle` subclass + `public sealed
    class … : IDisposable` block to @ref document::types on destruction — the
    driver has no explicit "finish class" hook, so RAII is the finalizer.
    Move-only so a moved-from temporary does not double-flush. The paired native
    thunks and P/Invoke declarations were already appended (flatly) to the
    document as each member was emitted. */
struct class_writer {
    document* doc{nullptr};
    std::string cs_name{};        /**< The C# class name. */
    std::string doc_text{};       /**< The class summary doc. */
    std::string cpp_qualified{};  /**< The `::`-qualified C++ type (anchor spelling). */
    std::string sym_prefix{};     /**< The `welder_<path>` C-symbol prefix. */
    std::string destroy_symbol{}; /**< The `welder_…_destroy` symbol. */
    std::string members{};        /**< Accumulated property/method/ctor text. */

    class_writer() = default;
    class_writer(const class_writer&) = delete;
    class_writer& operator=(const class_writer&) = delete;
    class_writer(class_writer&& o) noexcept { *this = std::move(o); }
    class_writer& operator=(class_writer&& o) noexcept {
        doc = o.doc;
        cs_name = std::move(o.cs_name);
        doc_text = std::move(o.doc_text);
        cpp_qualified = std::move(o.cpp_qualified);
        sym_prefix = std::move(o.sym_prefix);
        destroy_symbol = std::move(o.destroy_symbol);
        members = std::move(o.members);
        o.doc = nullptr;
        return *this;
    }
    ~class_writer() {
        if (!doc)
            return;
        std::string& out{doc->types};
        // The per-class SafeHandle: ReleaseHandle calls the destroy thunk, so
        // finalization and Dispose share one release path.
        out += "    internal sealed class " + cs_name +
               "Handle : SafeHandle\n    {\n"
               "        internal " + cs_name +
               "Handle(IntPtr handle, bool owns) : base(IntPtr.Zero, owns)\n"
               "        {\n            SetHandle(handle);\n        }\n"
               "        public override bool IsInvalid => handle == "
               "IntPtr.Zero;\n"
               "        protected override bool ReleaseHandle()\n"
               "        {\n            NativeMethods." + destroy_symbol +
               "(handle);\n            return true;\n        }\n"
               "    }\n\n";
        emit_doc_comment(out, "    ", doc_text.empty() ? nullptr : doc_text.c_str());
        out += "    public sealed class " + cs_name + " : IDisposable\n    {\n";
        out += "        internal " + cs_name + "Handle _handle;\n";
        out += "        internal " + cs_name +
               "(IntPtr handle, bool owns) { _handle = new " + cs_name +
               "Handle(handle, owns); }\n\n";
        out += members;
        out += "        public void Dispose() => _handle.Dispose();\n";
        out += "    }\n\n";
    }
};

/** An enum handle: a C# `enum : <underlying>` accumulated by `add_enumerator`,
    flushed by RAII (same rationale as @ref class_writer). No native thunks — an
    enum crosses as its underlying value. */
struct enum_writer {
    document* doc{nullptr};
    std::string cs_name{};
    std::string doc_text{};
    std::string underlying{}; /**< The C# underlying-type spelling (`int`, …). */
    std::string values{};     /**< Accumulated `        Name = value,` lines. */

    enum_writer() = default;
    enum_writer(const enum_writer&) = delete;
    enum_writer& operator=(const enum_writer&) = delete;
    enum_writer(enum_writer&& o) noexcept { *this = std::move(o); }
    enum_writer& operator=(enum_writer&& o) noexcept {
        doc = o.doc;
        cs_name = std::move(o.cs_name);
        doc_text = std::move(o.doc_text);
        underlying = std::move(o.underlying);
        values = std::move(o.values);
        o.doc = nullptr;
        return *this;
    }
    ~enum_writer() {
        if (!doc)
            return;
        std::string& out{doc->types};
        emit_doc_comment(out, "    ", doc_text.empty() ? nullptr : doc_text.c_str());
        out += "    public enum " + cs_name + " : " + underlying + "\n    {\n";
        out += values;
        out += "    }\n\n";
    }
};

} // namespace welder::inline v0::rods::csharp
