// Generated by welder — C++ API reference (shadow header). Do not edit.
#pragma once

/** A small workshop: the docs-pipeline test corpus. */
namespace atelier {

/** A plain C++ extent; never bound to Python or Lua. */
struct Extent {
    Extent();
    /**
     * Build an extent from both sides.
     * @param w_ width in pixels
     * @param h_ height in pixels
     */
    Extent(int w_, int h_);
    /** width in pixels */
    int w;
    int h;
    /**
     * The covered surface.
     * @return w times h
     */
    int area() const;
    /** A square extent. */
    static atelier::Extent square(int side);
    atelier::Extent operator+(const atelier::Extent& o) const;
};

/** Bound to Python opt-in; documented in C++ regardless. */
struct Panel {
    Panel();
    int rows;
    int cols;
};

/** An extent with an id (public base shown, not flattened). */
struct Named : public atelier::Extent {
    Named();
    int id;
};

/** Compass headings (scoped). */
enum class Heading {
    North, ///< toward the top of the map
    East,
    South,
};

/** Signal levels (unscoped). */
enum Level {
    Low,
    High,
};

/**
 * Scale a value by a factor.
 * @param value the value to scale
 * @param factor the multiplier
 * @return value times factor
 */
int scale(int value, int factor);

/** The largest supported extent side, in pixels. */
extern const int max_side;

extern int instances;

/** Numeric helpers. */
namespace math {

/** @return the absolute value */
int magnitude(int v);

} // namespace math

} // namespace atelier
